### ISSUE TITLE
If redis restarts, lua scripts aren't reloaded

### ISSUE THREAD

**Issue by RyanGuthrie** [gresrun/jesque#100]
I am testing failure scenarios and currently if redis restarts, the lua scripts for jesque_pop.lua and jesquelpoplpush.lua aren't reloaded and thus requires the worker to terminate.

**Comment by argvk** [comment]
@RyanGuthrie for the test scenario, what were the aof and rdb settings ?

**Comment by RyanGuthrie** [comment]
Neither are on.

**Comment by lpfeup** [comment]
I also had a worker terminated on a redis restart:
```
[WARN] [net.greghaines.jesque.worker.WorkerImpl] Terminating in response to exception
redis.clients.jedis.exceptions.JedisNoScriptException: NOSCRIPT No matching script. Please use EVAL.
```

Any updates regarding this issue?

**Comment by tj---** [comment]
Hi there. Thank you for the fix. Is a release planned anytime soon - we are eagerly waiting for it?
