### ISSUE TITLE
How do I inject spring bean into a job

### ISSUE THREAD

**Issue by jaychang9** [gresrun/jesque#118]
When I tried use @Autowired to inject a spring bean to Job,It show me 
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'returProductStoreJob' defined in file [E:\EclipseWorkSpaceFolder\MyWorkspace\jesquedemo\target\classes\cn\jaychang\jesquedemo\ch03\ReturProductStoreJob.class]: Could not resolve matching constructor (hint: specify index/type/name arguments for simple parameters to avoid type ambiguities)`

Job class I use @Scope("prototype") and @Component annotation

**Comment by berlinguyinca** [comment]
Could we please have a response to this question?

kind regards
