### ISSUE TITLE
What was changed in the jesque-2.1.2 release?

### ISSUE THREAD

**Issue by edwardotis** [gresrun/jesque#121]
I'm curious what was changed in the jesque-2.1.2 release? There are no corresponding notes on that particular release.
https://github.com/gresrun/jesque/releases

**Comment by ofirnk** [comment]
[This](https://github.com/gresrun/jesque/compare/jesque-2.1.1...jesque-2.1.2) would be a good summary :)

**Comment by gresrun** [comment]
Added release documentation for v2.1.2.
