### ISSUE TITLE
Batch job queuing?

### ISSUE THREAD

**Issue by vincentjames501** [gresrun/jesque#123]
It would be nice to add to the `Client` interface the ability to batch queue jobs. In our case we need to batch queue around 40-100k jobs and it would be nice to do it in a single pipeline w/ Jedis.

```java
void enqueue(String queue, List<Job> jobs); // Or Job...
```

**Comment by wbijen** [comment]
` public static void doBulkEnqueue(Jedis jedis, String namespace, String queue, List<String> jobJsonList) {
        jedis.sadd(JesqueUtils.createKey(namespace, new String[]{"queues"}), new String[]{queue});
        Pipeline pipeline = jedis.pipelined();
        String key = JesqueUtils.createKey(namespace, new String[]{"queue", queue});
        if (jobJsonList.size() > 500) {
            int i = 0;
            Iterator it = jobJsonList.iterator();

            while(it.hasNext()) {
                String jobJson = (String)it.next();
                jedis.rpush(key, new String[]{jobJson});
                ++i;
                if (i == 500) {
                    pipeline.sync();
                    pipeline = jedis.pipelined();
                    i = 0;
                }
            }

            pipeline.sync();
        } else {
            Iterator var9 = jobJsonList.iterator();

            while(var9.hasNext()) {
                String jobJson = (String)var9.next();
                jedis.rpush(key, new String[]{jobJson});
            }

            pipeline.sync();
        }

    }`

**Comment by wbijen** [comment]
```
 public static void doBulkEnqueue(Jedis jedis, String namespace, String queue, List<String> jobJsonList) {
        jedis.sadd(JesqueUtils.createKey(namespace, new String[]{"queues"}), new String[]{queue});
        Pipeline pipeline = jedis.pipelined();
        String key = JesqueUtils.createKey(namespace, new String[]{"queue", queue});
        if (jobJsonList.size() > 500) {
            int i = 0;
            Iterator it = jobJsonList.iterator();

            while(it.hasNext()) {
                String jobJson = (String)it.next();
                jedis.rpush(key, new String[]{jobJson});
                ++i;
                if (i == 500) {
                    pipeline.sync();
                    pipeline = jedis.pipelined();
                    i = 0;
                }
            }

            pipeline.sync();
        } else {
            Iterator var9 = jobJsonList.iterator();

            while(var9.hasNext()) {
                String jobJson = (String)var9.next();
                jedis.rpush(key, new String[]{jobJson});
            }

            pipeline.sync();
        }

    }
```
