### ISSUE TITLE
jackson databind 2.9 includes a breaking change

### ISSUE THREAD

**Issue by maladon** [gresrun/jesque#137]
Jackson databind DeserializationConfig in 2.9 does not have a with() that has DateFormat included. This call is attempted in ObjectMapper's static initializer. This breaks anyone with more recent Spring versions.

2.9:
http://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/DeserializationConfig.html

2.8:
http://fasterxml.github.io/jackson-databind/javadoc/2.8/com/fasterxml/jackson/databind/DeserializationConfig.html

**Comment by husnjak** [comment]
I fixed it by forking and creating a new release
here is my fork: https://github.com/husnjak/jesque

I used jitpack to download the jar using gradle: https://jitpack.io/#husnjak/jesque/2.1.2-hus
```
dependencies {
	        compile 'com.github.husnjak:jesque:2.1.2-hus'
	}
```

**Comment by bbpennel** [comment]
It looks like this was addressed on master about 5 months ago https://github.com/gresrun/jesque/blame/master/src/main/java/net/greghaines/jesque/json/ObjectMapperFactory.java#L36
Are there plans to do an official release soon?

**Comment by rteabeault** [comment]
I am having this issue as well. Can we get a public release of this fix?

**Comment by gresrun** [comment]
Version 2.1.3 should be on Maven Central in a few hours.
