### ISSUE TITLE
why does jesque not use namespace as prefix for recurring jobs?

### ISSUE THREAD

**Issue by f9865** [gresrun/jesque#158]
Hi, @argvk @gresrun 
I'm trying to understand how does jesque work by reading code.
But I was wondering why doesn't JesqueUtils::createRecurringHashKey use namespace as prefix, when it creates redis key for recurring jobs. It seems like that jesque always use namespace as prefix to figure out jobs belong to different applications.
https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/utils/JesqueUtils.java#L98
If there are two different gRPC services use the same redis instance for jesque and they both have recurring jobs, will they take jobs from the same queue? 
Thanks

**Comment by argvk** [comment]
Hey @f9865.
> But I was wondering why doesn't JesqueUtils::createRecurringHashKey use namespace as prefix, when it creates redis key for recurring jobs.

it does, you can see on [this line](https://github.com/gresrun/jesque/blob/02e3af9f98e0d02c284a9d6b8c97daae5ba1cb16/src/main/java/net/greghaines/jesque/client/AbstractClient.java#L390) that `hashKey` is created from the `queueKey` itself. 

> If there are two different gRPC services use the same redis instance for jesque and they both have recurring jobs, will they take jobs from the same queue?

yes, you can have multiple services as consumers for the same recurring job. 

Hope that helped!

**Comment by f9865** [comment]
Appreciate your reply. This does help a lot.
