### ISSUE TITLE
Jedis 3.X compatibility

### ISSUE THREAD

**Issue by bountin** [gresrun/jesque#161]
The current master already supports the breaking API changes of Jedis 3 but isn't released yet. Could you do this, so that we don't have to create special builds?

**Comment by kjwise** [comment]
Yes please

**Comment by arron86** [comment]
Please...

**Comment by samekim** [comment]
+1

**Comment by bbpennel** [comment]
Releasing this would be very helpful :)

**Comment by bountin** [comment]
Ping @gresrun.

**Comment by nipun-gupta-e3183** [comment]
any update on releasing this?

**Comment by welkinbai** [comment]
+1

**Comment by shahdewang** [comment]
+1

**Comment by gresrun** [comment]
Fixed in [release 2.2.0](https://github.com/gresrun/jesque/releases/tag/jesque-2.2.0).
