### ISSUE TITLE
How to run workers / best practice for cleaning up

### ISSUE THREAD

**Issue by ruckus** [gresrun/jesque#3]
Is there a best practice to running worker(s) and cleaning up? 

I currently run a worker like so:

``` java
      final Worker worker = new WorkerImpl(jesqueConfig, Arrays.asList(queue), Arrays.asList(PhotoUploadActivity.class));
      Thread t = new Thread(worker);
      t.start();
      t.join();
```

And this seems to work just fine. However the only way for me to cancel the process is to send it a signal, either a TERM or USR{1,2}.

If I look in resque (via resque-web) I can see that there are multiple of these Java workers that just accrue up - they are not getting pruned.

Thus - whats the best practice to gracefully shutting down the runtime container for workers?. I've added a JVM shutdown hook which attempts to call `worker.end(true)` but this never seems to get called.

**Comment by vincentjames501** [comment]
I think this should be brought back up. Looks like resque is using heart beats (see `prune_dead_workers`):

https://github.com/resque/resque/blob/e0f850f087160362cec1ae3759c7c1e1d9190381/lib/resque/worker.rb#L587
