### ISSUE TITLE
Recover failed job

### ISSUE THREAD

**Issue by nottix** [gresrun/jesque#54]
There is an issue when a job fails. 
1. Job was submited
2. the worker starts to process this job and crash before complete it. Eg: The worker machine shutdown.
3. The job remains in the working queue forever.

Is it possibile?

**Comment by krsinghshubham** [comment]
I understand the part that the job might not be idempotent, but there should be a native mechanism to re-enqueue explicitly or a default retry count defined for each worker which can be set by default to 0?
