### ISSUE TITLE
AdminClient ignores any redis sentinel settings

### ISSUE THREAD

**Issue by peh** [gresrun/jesque#60]
As the AdminClientImpl is connecting directly to host:port given from the Config, we are not able to use Jesque with a redis-sentinel setup.

**Comment by ctoestreich** [comment]
I have submitted [Pull Request 79](https://github.com/gresrun/jesque/pull/79)

**Comment by gresrun** [comment]
@peh FYI, this is now in the latest SNAPSHOT thanks to @ctoestreich.

**Comment by peh** [comment]
yeah. i never did the PR as we never had any chance to test the stuff. thank you for your work @ctoestreich !
