### ISSUE TITLE
Redis username configuration

### ISSUE THREAD

**Issue by dwilkie** [gresrun/jesque#67]
I'm using RedisToGo and the Redis URL that I need to connect to is of the form:

```
redis://user:password@subdomain.redistogo.com:9259/
```

I can see that the ConfigBuilder accepts a `withPort`, `withHost` and `withPassword` but it does not provide a `withUser`.

FYI have the following code to extract the details from the REDIS_PROVIDER_URL (compatible with Sidekiq)

```java
    final ConfigBuilder configBuilder = new ConfigBuilder();

    try {
      URI redisUrl = new URI(System.getProperty("REDIS_PROVIDER", "127.0.0.1"));

      String redisHost = redisUrl.getHost();
      int redisPort = redisUrl.getPort();
      String redisUserInfo = redisUrl.getUserInfo();

      if (redisHost != null) {
        configBuilder.withHost(redisHost);
      }

      if (redisPort > -1) {
        configBuilder.withPort(redisPort);
      }

      if (redisUserInfo != null) {
        configBuilder.withPassword(redisUserInfo);
      }

      // need to split the UserInfo into username and password here and set it with:
      // configBuilder.withUser(); and  configBuilder.withUser();
    }
    catch (URISyntaxException e) {
      System.err.println(e.toString());
      System.exit(1);
    }

    final Config config = configBuilder.build();
```

**Comment by gresrun** [comment]
Redis doesn't support usernames, [it only supports passwords](http://redis.io/topics/security) It looks like you only use the password, according to [this RedisToGo support page](http://support.redistogo.com/kb/redistogocom/introduction-to-redis). (NOTE: Jesque uses Jedis to connect to Redis)
