### ISSUE TITLE
Keep alive connection

### ISSUE THREAD

**Issue by dwilkie** [gresrun/jesque#70]
I'm using the `ClientImpl` like show below but I'm still getting timeouts:

```java
    final net.greghaines.jesque.client.Client jesqueMtClient = new net.greghaines.jesque.client.ClientImpl(
      jesqueConfig, 15, 15,
      java.util.concurrent.TimeUnit.SECONDS
    );
```

In `ClientImpl` on https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/client/ClientImpl.java#L92 `checkConnectionBeforeUse` is set to `false`. However on https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/client/ClientImpl.java#L155 the method that ensures the jedisConnection is open only runs if `checkConnectionBeforeUse` is set to `true`

```java
    private void ensureJedisConnection() {
        if (this.checkConnectionBeforeUse && !JedisUtils.ensureJedisConnection(this.jedis)) {
            authenticateAndSelectDB();
        }
    }
```

I'm wondering if this is a bug or whether it's intentional. If it's intentional is there another way in which I should be keeping the connection open?

Thanks again for your help.

**Comment by gresrun** [comment]
Hmmm, it looks like a bug to me. It looks like I introduced it 2.5 years ago in 19989fb !

**Comment by gresrun** [comment]
My suggestion would be to try changing the keep-alive runner to have the following:
```java
if (!JedisUtils.ensureJedisConnection(jedis)) {
    authenticateAndSelectDB();
}
```
instead of:
```java
ensureJedisConnection();
```
If that works, I'll commit a fix.

**Comment by dwilkie** [comment]
Yep that would be fine but maybe you could simpley change the following in the constructor on line https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/client/ClientImpl.java#L92

```java
  this.checkConnectionBeforeUse = true;
```

This would ensure that the other constructor works as expected as well

**Comment by gresrun** [comment]
The whole reason for the second constructor is that the reconnection logic happens on a separate thread and not on the thread performing the client work. by setting `this.checkConnectionBeforeUse = false`, we prevent the client thread from doing any work in `ensureJedisConnection()`. The bug was that the reconnection thread wasn't doing any work, either!

**Comment by dwilkie** [comment]
Ah I see! Then I think your suggestion will work fine.
