### ISSUE TITLE
Using ensureJedisConnection(); in the Pool

### ISSUE THREAD

**Issue by dwilkie** [gresrun/jesque#72]
Hi, 

Just wondering if it's possible to use `ensureJedisConnection()` to ensure the pool connection is open before enqueuing a job in [ClientPoolImpl](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/client/ClientPoolImpl.java) as it's currently used in [ClientImpl](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/client/ClientImpl.java)

If it's not currently possible I will submit a PR to add this functionality. Anything special I need to know?

**Comment by gresrun** [comment]
@dwilkie I'm not sure I'm following. Each of the operations in ClientPoolImpl use [PoolUtils.doWorkInPool](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/utils/PoolUtils.java#L48) which acquires a valid Jedis from the pool, performs the operation with that connection then returns the connection back to the pool. The pool should never provide an invalid Jedis; are you experiencing an issue with it?

**Comment by gresrun** [comment]
@dwilkie Is this an issue for you? Or was this a pre-emptive question?

**Comment by dwilkie** [comment]
I just implemented this today and it appears to be working as you said. The key is on [this line](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/utils/PoolUtils.java#L101) where you set `cfg.setTestOnBorrow(true)`.

I'll submit a PR to document this how to set up a `ClientPoolImpl`.

Thanks for your help by the way!

**Comment by dwilkie** [comment]
I'm having an issue which I think is related to bad connections in the pool.

On setup I'm creating a `JedisClient` like shown below then enqueuing jobs to it normally.

```java
final Client jesqueMtClient = ClientPoolImpl(
  jesqueConfig,
  createJedisPool(jesqueConfig)
);
```
This works great for a few hours then after a while it just stops enqueuing jobs with no exception raised. Reading through the Jedis code I noticed that the [JedisPool](https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/util/Pool.java) uses an Internal [GenericObjectPool](https://commons.apache.org/proper/commons-pool/api-1.6/org/apache/commons/pool/impl/GenericObjectPool.html).

The value of `DEFAULT_WHEN_EXHAUSTED_ACTION` in [GenericObjectPool](https://commons.apache.org/proper/commons-pool/api-1.6/org/apache/commons/pool/impl/GenericObjectPool.html) is `WHEN_EXHAUSTED_BLOCK` and I can't see `setWhenExhaustedAction` being called anywhere, so i'm assuming that when the Pool is exhausted all it will block.

However in `PoolUtil` on [this line](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/utils/PoolUtils.java#L97) you set `cfg.setMaxTotal(-1); // Infinite` so from my understanding it should never be exhausted and block?

Any clues  / advise to figure out what's going on here?

**Comment by dwilkie** [comment]
Just saw this as well https://github.com/xetorthio/jedis/issues/368 but it looks like you return the resource to the pool here: https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/utils/PoolUtils.java#L60

**Comment by gresrun** [comment]
I am calling `cfg.setBlockWhenExhausted(false);` [JavaDoc for that method](https://commons.apache.org/proper/commons-pool/api-2.3/org/apache/commons/pool2/impl/BaseObjectPoolConfig.html#setBlockWhenExhausted(boolean)) (Note that Jesque uses commons-pool v2.3 so `setWhenExhausedAction` is not a valid method.) and I'm always returning the resource to the pool, as you noted.

Can you give me a stack trace of the application when you're in the state you described?
(On a *nix system you can use `kill -3 <pid>` and it will cause Java to print all the current threads' stack traces to that process' stdout)

**Comment by gresrun** [comment]
@dwilkie Were you able to get a stack trace while this error was occurring?

**Comment by dwilkie** [comment]
I figured out that the issue I was having had nothing to do with Jesque. The code that was enqueuing the job wasn't being executed. Thanks for your tip about `kill -3 <pid>`! by the way helped me to solve the problem!

**Comment by gresrun** [comment]
Glad you found the problem!
