### ISSUE TITLE
When my worker crash or use kill -9 to kill it...

### ISSUE THREAD

**Issue by damacheng009** [gresrun/jesque#84]
127.0.0.1:6379> KEYS *
1) "resque:queue:foo"
2) "resque:worker:SDJS-20150805CG:5796-0:JAVA_DYNAMIC_QUEUES,foo:started"
3) "resque:queues"
4) "resque:workers"
5) "resque:stat:processed"
127.0.0.1:6379> smembers resque:workers
1) "SDJS-20150805CG:5796-0:JAVA_DYNAMIC_QUEUES,foo"

There is some useless data in Redis database..Can we have to manually delete the data..

**Comment by gresrun** [comment]
Yes, this will happen if the process dies a terrible death. Not much can be done besides manually cleaning it up.

**Comment by hrchu** [comment]
Can the redis features: expire/notification help this? 
http://redis.io/commands/expire
http://redis.io/topics/notifications
