### ISSUE TITLE
Question about worker shutdown

### ISSUE THREAD

**Issue by pierredavidbelanger** [gresrun/jesque#85]
This is more a question than an issue.

I am very pleased to have found this great lib (and [this one too](https://github.com/technoweenie/coffee-resque) as my front end is Node.js based)!
I am playing with it, and plan to use it in production soon, to replace RabbitMQ (too complex for my simple needs).

One thing bugs me right now, and its the corner case where Heroku shuts down my worker (Heroku send a `SIGTERM` to the JVM and wait 10 seconds to allows it to cleanly shutdown).

So, in my code I have this, to force jesque to end the workers right now when JVM is tell to shutdown:
```java
Runtime.getRuntime().addShutdownHook(new Thread(() -> {
    try {
        workerPool.endAndJoin(true, 5000);
    } catch (InterruptedException e) {
        System.err.println("Interrupted while waiting for worker pool to end, expect the shit to hit the fan!");
    }
}));
```

My worker is implemented like this:
```java
public static class TestJob implements Callable<Void> {

    private final String id;

    public TestJob(String id) {
        this.id = id;
    }

    @Override
    public Void call() throws Exception {
        try {
            for (int i = 0; i < 300; i++) {
                System.out.println("pretend to work hard on job " + id);
                Thread.sleep(1000);
                // in the extreme case interrupted happens outside of the sleep
                if (Thread.currentThread().isInterrupted())
                    throw new InterruptedException();
            }
        } catch (InterruptedException e) {
            // TODO: my application logic to handle job interruption
            // also tell jesque we were interrupted (job will will go back to its queue)
            throw e;
        } catch (Exception e) {
            // tell jesque something bad happened (job will go into the failed queue)
            throw e;
        }
        return null;
    }
}
```

This seems to work correctly, sending a `SIGTERM` (`CTRL-c` foreman) will correctly send the jobs back to their respective queue. BUT, jobs are also put into the failed queue.

I wonder if this is expected (I guess yes, because of [this catch all](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/worker/WorkerImpl.java#L560)) and if there is a way to prevent this (I do not want my interrupted jobs to go to the failed queue) ?

Why not catching `InterruptedException` as a special case here ?:
```java
try {
    // ...
    final Object result = execute(job, curQueue, instance);
    success(job, instance, result, curQueue);
} catch (InterruptedException interrupted) {
    // ignore or logs, anything but do not consider this a failure <---
} catch (Throwable thrwbl) {
    failure(thrwbl, job, curQueue);
} finally {
    removeInFlight(curQueue);
    // ...
}
```

I hope this is clear.

Also thank you for this great lib!

**Comment by pierredavidbelanger** [comment]
Maybe a more "clean" way of solving my problem is this: make [WorkerImpl.failure](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/worker/WorkerImpl.java#L629) consider a `null` return from [FailQueueStrategy.getFailQueueKey](https://github.com/gresrun/jesque/blob/master/src/main/java/net/greghaines/jesque/worker/FailQueueStrategy.java#L32) as an intent to NOT put the job in any failed queue ?

I can send a PR if you want.

**Comment by pierredavidbelanger** [comment]
In the meantime (using the `2.0.2` release), I work around the "issue" with this hack:

I have my own `WorkerImpl` subclass that handle failure caused by `InterruptedException` in a special way (by doing nothing):
```java
public class InterruptionAwareWorkerImpl extends WorkerImpl {

    public InterruptionAwareWorkerImpl(Config config, Collection<String> queues, JobFactory jobFactory) {
        super(config, queues, jobFactory);
    }

    @Override
    protected void failure(Throwable t, Job job, String curQueue) {
        if (t instanceof InterruptedException) return;
        super.failure(t, job, curQueue);
    }
}
```

Coupled with my own `workerFactory`:
```java
Callable<WorkerImpl> workerFactory = () ->
        new InterruptionAwareWorkerImpl(config, Collections.singleton(queue), jobFactory);
```

**Comment by gresrun** [comment]
@pierredavidbelanger Thanks for the great suggestion and thorough explanation! I'm glad Jesque is helping you make great software. Merged.
