### ISSUE TITLE
A CLI for Jesque

### ISSUE THREAD

**Issue by pierredavidbelanger** [gresrun/jesque#88]
I made a small [Jesque CLI](https://github.com/pierredavidbelanger/jesque-cli) for myself to abstract away some logic related to job queuing/processing (mainly to be used locally, but it can also be useful with Heroku.)

If you are interested, I can prepare a PR that merge the project into yours (into a `net.greghaines.jesque.cli` package for example).

This will introduce a new dependency to `com.beust:jcommander` though (for the command-line arguments parsing.)

If you prefer, this could be a separated project.

Or also, obviously, I can try to maintain it myself :)

**Comment by gresrun** [comment]
Could I see what you're proposing somewhere?
