### ISSUE TITLE
ClassCastException java.lang.Long cannot be cast to [B

### ISSUE THREAD

**Issue by ronankim** [gresrun/jesque#90]
I often get this error both from WorkerImpl and ClientImpl.（Regarding this post: https://github.com/xetorthio/jedis/issues/186 ）

Is it feasible for both WorkerImpl and ClientImpl use pool connection rather than single Jedis instance? Or is there a way to avoid frequently recreating WorkerImpl and ClientImpl?

**Comment by gresrun** [comment]
@ronankim According to xetorthio/jedis#186, the issue was due to using `Pool.returnResource()` instead of `Jedis.close()`. Can you confirm this fixes your issue?
